name: Add comment via ChatGPT

on:
  issues:
    types: [opened]

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - id: chat
        name: Generated comment via ChatGPT
        uses: aahl/chatgpt-action@main
        with:
          api_base: ${{ secrets.CHATGPT_API_BASE }}
          api_key: ${{ secrets.CHATGPT_API_KEY }}
          model: deepseek-v3
          prompt: |
            You are a Github issue assistant, please answer this question.
          message: |
            # ${{ github.event.issue.title }}
            ${{ github.event.issue.body }}

            > This is the title (first line) and content of the issue submitted by the user.
            > The reply must be in the language of the "issue details" content, or in the language of the title if no content details are provided, and in English if it is unclear.
            > If the issue feedback is about a problem with a specific device, check if the user has provided the device model,
            > entity attributes, and ha logs; remind the user if they have not provided this information.

      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.chat.outputs.REPLY }}
